apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nebutra

resources:
  - namespace.yaml
  # - deployments/
  # - services/
  # - configmaps/

commonLabels:
  app.kubernetes.io/part-of: nebutra-sailor
  app.kubernetes.io/managed-by: kustomize
